### ISSUE TITLE
No graphs loaded yet

### ISSUE THREAD

**Issue by serverok** [pmaji/crypto-whale-watching-app#106]
I installed at

http://whaledectector.com

Site missing CSS, shows no graph. 

On console, i get error "No graphs loaded yet".

![screenshot from 2018-09-14 08-09-21](https://user-images.githubusercontent.com/34412323/45526647-a05b2b00-b7f5-11e8-9f8c-05c42057cefc.png)

Any idea why it is not wokring ?

@pmaji

**Comment by serverok** [comment]
Thanks for the reply.  I just run it like local hosting, changed port in script to 80, then run it inside tmux.

Maybe it take some time to come up, here is what i am getting in the console. I see a ZeroDivisionError error, not sure if this is critical or not.

```
Going to kill Web socket from LTC-USD
Restarting pair Web socket GDAX ETH-USD
Exception in thread Thread-187:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "app.py", line 727, in websockThread
    kill = 5 / pair.webSocketKill
ZeroDivisionError: division by zero

69.254.185.213 - - [13/Sep/2018 22:43:24] "GET /favicon.ico HTTP/1.1" 200 -
22:43:22  :   Ms Diff for LTC-USD is 1816083 Total refreshes for pair 380
Initializing order Book websocket for ETH-USD
22:43:22  :   Ms Diff for ETH-USD is 2199157 Total refreshes for pair 431
Empty data for GDAXLTC-USD Will wait 3s
Restarting pair Web socket GDAX LTC-USD
-- Subscribed! --

Empty data for GDAXETH-USD Will wait 3s
Initializing order Book websocket for LTC-USD
Watchdog got some bad sheeps back to group
-- Subscribed! --

22:43:30  :   Ms Diff for LTC-EUR is 171061 Total refreshes for pair 65
22:43:30  :   Ms Diff for ETH-USD is 2207898 Total refreshes for pair 432
69.254.185.213 - - [13/Sep/2018 22:43:31] "POST /_dash-update-component HTTP/1.1" 200 -
Empty data for GDAXETH-USD Will wait 3s
22:43:31  :   Ms Diff for LTC-USD is 1825207 Total refreshes for pair 381
Empty data for GDAXLTC-USD Will wait 3s
69.254.185.213 - - [13/Sep/2018 22:43:34] "POST /_dash-update-component HTTP/1.1" 200 -
22:43:34  :   Ms Diff for ETH-USD is 2211858 Total refreshes for pair 433
Empty data for GDAXETH-USD Will wait 3s
22:43:35  :   Ms Diff for LTC-USD is 1829120 Total refreshes for pair 382
Empty data for GDAXLTC-USD Will wait 3s
```

**Comment by pmaji** [comment]
Hmm.. that is a little odd. I'm guessing it's something specific to the method of hosting if it's not something that is posing problems for folks who are running it locally. You haven't updated Plotly recently, have you? That was causing problems for folks running the most updated version as shown in the thread #103 . 

If you don't have success after waiting on it a bit or any further trouble shooting on your end, I'll have to phone a friend on this one -- @CrackLord who has previously hosted versions of this himself.

**Comment by serverok** [comment]
Thanks, i am running on server just like we run on local PC. Only differnce is host server have CentOS 7, everything else should be same as local PC.

> You haven't updated Plotly recently, have you? 

Not sure, i just run

pip3.6 install -r requirments.txt 

and have following python modules.

```
[root@s1 crypto-whale-watching-app]# pip3.6 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
bintrees (2.0.7)
certifi (2018.1.18)
chardet (3.0.4)
click (6.7)
dash (0.20.0)
dash-core-components (0.18.1)
dash-html-components (0.8.0)
dash-renderer (0.11.2)
decorator (4.2.1)
Flask (0.12.2)
Flask-Compress (1.4.0)
gdax (1.0.6)
idna (2.6)
ipython-genutils (0.2.0)
itsdangerous (0.24)
Jinja2 (2.10)
jsonschema (2.6.0)
jupyter-core (4.4.0)
MarkupSafe (1.0)
nbformat (4.4.0)
numpy (1.14.0)
pandas (0.22.0)
pip (9.0.1)
plotly (2.2.3)
python-dateutil (2.6.1)
pytz (2017.3)
requests (2.13.0)
setuptools (39.0.1)
six (1.10.0)
traitlets (4.3.2)
urllib3 (1.22)
websocket-client (0.40.0)
Werkzeug (0.14.1)
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@s1 crypto-whale-watching-app]# 
```

Python version is


```
[root@s1 crypto-whale-watching-app]# python3.6 --version
Python 3.6.5
[root@s1 crypto-whale-watching-app]# 
```

I will wait few hours and update

**Comment by theimo1221** [comment]
Hello Guys,
haven´t you seen this? The error is on purpose to stop broken threads from an other.
![image](https://user-images.githubusercontent.com/20605452/45594051-f7970200-b993-11e8-8533-20b2c7b1d7f7.png)

Best Regards

**Comment by theimo1221** [comment]
> Site missing CSS, shows no graph.  

We have no css yet, as that wasn´t our scope.

> On console, i get error "No graphs loaded yet".

The content you see shows its atleast partially working. As you might have noticed there is no .html in our code. 
`js_extern = "https://cdn.rawgit.com/pmaji/crypto-whale-watching-app/master/main.js"`  
Get´s loaded correctly and initiates the sidebar. So atleast the app Thread is working. 

After checking the requests and responses from your server it seems like your server network connection is real slow, or something is blocking the updating.

![image](https://user-images.githubusercontent.com/20605452/45594109-59a43700-b995-11e8-81bb-49c28b751bf2.png)

So that´s why you can´t see any graphs.

**Comment by serverok** [comment]
> haven´t you seen this? The error. The error is on purpose to stop broken threads from an other.

I don't know how this app works, so even if i noticed, it won't make much sense to me.  This is a critical error or just a warning ? Anyway i can avoid this error ?

> As you might have noticed there is no .html in our code.

So if i need to make it look pretty, i have to add HTML ?

> After checking the requests and responses from your server it seems like your server network connection is real slow, or something is blocking the updating.

Thanks, may be some networking issue or problem with CentOS 7 ? I will try on Ubuntu and see if it make any difference.

**Comment by pmaji** [comment]
@serverok did Ubuntu ever end up working for you?

**Comment by pmaji** [comment]
Just calling out here that this issue is still technically active and we are open to collaborators who wish to help us with the hosting of this web app, as per the README.
