### ISSUE TITLE
Errors appearing when hosting

### ISSUE THREAD

**Issue by CrackLord** [pmaji/crypto-whale-watching-app#53]
Hi guys, the syncing stopping problem is still an issue. When looking at the logs I discovered that they often print errors for different graphs like this:

```
127.0.0.1 - - [20/Feb/2018 04:07:42] "POST /_dash-update-component HTTP/1.0" 500 -
[2018-02-20 04:07:42,794] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/dash/dash.py", line 537, in dispatch
    for component_registration in self.callback_map[target_id]['inputs']:
KeyError: 'live-graph-ethbtc.figure'
```

**Comment by theimo1221** [comment]
But watchdog is restarting it isn't it?

**Comment by CrackLord** [comment]
I haven't implemented that change yet since I will wait till it's merged into master.

I wrote this before I knew that you had figured out the issue and had a solution ready :), so this is a separate problem.

**Comment by pmaji** [comment]
Alrighty; just merged it to master @CrackLord  @theimo1221 ... and now we wait haha.

**Comment by CrackLord** [comment]
> Alrighty; just merged it to master @CrackLord @theimo1221 ... and now we wait haha.

I have updated my server also with the new version, so hopefully this should be the end of the fresh issue.

**Comment by pmaji** [comment]
@CrackLord @theimo1221 Glory be I do believe it is working! I'm gunna give it a few more hours of me actively watching it and if it's still up before I hit the hay I'll close this issue.

**Comment by pmaji** [comment]
Closing as the new watchdog appears to be handling everything perfectly well.
